import * as THREE from 'three';

const earthTexture = new THREE.TextureLoader().load('textures/earth-texture.jpg');

function earthMesh() {

    const earthGeo = new THREE.SphereGeometry(25, 100, 100);
    const earthMaterial = new THREE.MeshStandardMaterial({ 
        map: earthTexture,
    });
    const earth = new THREE.Mesh(earthGeo, earthMaterial);
    const earthObj = new THREE.Object3D();
    earthObj.add(earth);
    earth.position.set(990, 0, 0);
    // earthGeo.rotateZ(-0.41)

    earth.name = 'Earth';
    earth.color = '#5AA7E8';

    earth.body = `Earth is the third planet from the Sun and the only known celestial body to support life. It has a diverse and dynamic environment with landmasses, oceans, and an atmosphere rich in oxygen and nitrogen. Earth's atmosphere protects life by absorbing harmful solar radiation and regulating temperature through the greenhouse effect. The planet’s surface is 71% water, which plays a crucial role in sustaining ecosystems. Earth has a magnetic field generated by its iron core, which shields it from solar winds and cosmic radiation. It experiences geological activity, including earthquakes and volcanic eruptions, driven by plate tectonics. Earth's biodiversity is vast, with millions of known species and likely many more undiscovered. The planet has one natural satellite, the Moon, which influences tides and stabilizes Earth’s axial tilt. Over billions of years, Earth has undergone significant changes, from ice ages to periods of global warming. Human activity, particularly industrialization and deforestation, has accelerated climate change, threatening ecosystems worldwide. Space exploration efforts continue to study Earth from orbit, providing valuable data on weather patterns and environmental changes. As humanity advances technologically, efforts to preserve Earth's resources and explore space for potential colonization are increasingly important.`;
    
    return { earthGeo, earthMaterial, earth, earthObj }

}

export default earthMesh;